// SPDX-License-Identifier: Apache-2.0

//! Packaged Substrait extension files.
//!
//! This crate bundles the Substrait specification's extension YAML files, the
//! text-based JSON schemas, and the function test cases, alongside Rust types
//! generated from the schemas with [`typify`](https://docs.rs/typify).
//!
//! Versions of this crate correspond to Substrait
//! [releases](https://github.com/substrait-io/substrait/releases).
//!
//! - [`text`] — types generated from the text schemas (e.g.
//!   [`text::simple_extensions::SimpleExtensions`]), plus the raw schema
//!   sources as consts (e.g. `text::SIMPLE_EXTENSIONS_SCHEMA`) for consumers
//!   that validate raw YAML against the JSON schema.
//! - [`extensions`] — the embedded extension YAML files, the
//!   [`extensions::EXTENSIONS`] map (keyed by file stem to the parsed
//!   extension), and the [`extensions::SIMPLE_EXTENSIONS`] slice (keyed by URN
//!   to the raw YAML source).
//! - [`testcases`] — the embedded function test case files.
//! - [`examples`] — the embedded example extension and type YAML files from the
//!   specification's documentation. These are illustrations, not catalog
//!   entries: they are deliberately absent from [`extensions::EXTENSIONS`] and
//!   [`extensions::SIMPLE_EXTENSIONS`], their URNs use the
//!   `extension:org.example:` owner, and they carry no compatibility guarantee.
//!   They are useful as fixtures for testing an extension parser.

/// Types generated from the Substrait text-based JSON schemas, plus the raw
/// schema sources as `&str` consts (e.g. `SIMPLE_EXTENSIONS_SCHEMA`).
#[allow(
    unused_variables,
    clippy::clone_on_copy,
    clippy::derivable_impls,
    clippy::needless_borrow,
    clippy::explicit_auto_deref,
    clippy::to_string_trait_impl,
    clippy::uninlined_format_args
)]
pub mod text {
    include!(concat!(env!("OUT_DIR"), "/substrait_text.rs"));
}

/// The embedded Substrait core extension YAML files.
///
/// The contents of this module are auto-generated by `build.rs` and kept in
/// sync with the packaged extension files.
pub mod extensions {
    include!(concat!(env!("OUT_DIR"), "/extensions.in"));
}

/// The embedded Substrait function test case files.
pub mod testcases {
    use include_dir::{include_dir, Dir};

    /// The directory tree of `.test` function test case files.
    pub static TESTCASES: Dir<'static> = include_dir!("$CARGO_MANIFEST_DIR/testcases");
}

/// The embedded example extension and type YAML files.
///
/// These come from the specification's documentation (`site/examples`) and are
/// illustrations of the simple-extension format, not entries in the Substrait
/// extension catalog. They are not registered in [`extensions::EXTENSIONS`] or
/// [`extensions::SIMPLE_EXTENSIONS`], and their contents and URNs may change
/// without a deprecation cycle.
pub mod examples {
    use include_dir::{include_dir, Dir};

    /// The directory tree of example `.yaml` files, under `extensions/` and
    /// `types/`.
    pub static EXAMPLES: Dir<'static> = include_dir!("$CARGO_MANIFEST_DIR/examples");
}
