version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
    groups:
      java-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/python/substrait-protobuf"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/python/substrait-antlr"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/python/substrait-extensions"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"
