#!/usr/bin/env sh
set -eu

# Regenerates the committed Rust ANTLR parsers from the Substrait grammar.
#
# Unlike the protobuf and extensions crates (which generate at build time), the
# Rust ANTLR target requires a forked ANTLR build that is not a cargo build
# dependency, so the generated parsers are committed to the repository. This
# script downloads that forked ANTLR JAR and runs it. It requires `java`.

SUBSTRAIT_HOME="${SUBSTRAIT_HOME:-../../substrait}"
GRAMMAR_DIR="$SUBSTRAIT_HOME/grammar"
JAVA="${JAVA:-java}"

# The Rust bindings for ANTLR are not official, so we use a forked ANTLR build.
ANTLR_URL="https://github.com/antlr4rust/antlr4/releases/download/v0.5.0/antlr4-4.13.3-SNAPSHOT-complete.jar"
ANTLR_SHA256="8227a91d45625aec824e31cc7792ecb8b22b973da71f2396e81542b88d897d8f"
ANTLR_JAR="antlr/antlr.jar"

TYPE_TARGET="src/substrait_type"
FTEST_TARGET="src/func_test_case"

echo "Generating Rust ANTLR parsers from $GRAMMAR_DIR"

# Download and verify the forked ANTLR JAR (cached in antlr/, gitignored).
mkdir -p antlr
if [ ! -f "$ANTLR_JAR" ]; then
    echo "Downloading forked ANTLR JAR..."
    curl -fsSL -o "$ANTLR_JAR" "$ANTLR_URL"
fi
if command -v sha256sum >/dev/null 2>&1; then
    echo "$ANTLR_SHA256  $ANTLR_JAR" | sha256sum -c -
else
    echo "$ANTLR_SHA256  $ANTLR_JAR" | shasum -a 256 -c -
fi

# Copy the grammars into a temporary working directory (ANTLR spams extra files
# next to the grammar).
rm -rf tmp
mkdir -p tmp
cp "$GRAMMAR_DIR"/*.g4 tmp/

# Generate the parsers. The type grammar is a combined grammar; the test case
# grammar is split into a lexer and parser grammar.
(cd tmp && "$JAVA" -jar ../"$ANTLR_JAR" -Dlanguage=Rust SubstraitLexer.g4 SubstraitType.g4)
(cd tmp && "$JAVA" -jar ../"$ANTLR_JAR" -Dlanguage=Rust FuncTestCaseLexer.g4 FuncTestCaseParser.g4)

# The forked ANTLR emits a doubled name for parser grammars whose name ends in
# "Parser" (`FuncTestCaseParserParserContext`); fix it up to the real trait.
sed -i.bak 's/FuncTestCaseParserParserContext/FuncTestCaseParserContext/g' \
    tmp/functestcaseparser.rs
rm -f tmp/functestcaseparser.rs.bak

# Prepend an SPDX header and lint suppressions to each generated file.
header() {
    printf '// SPDX-License-Identifier: Apache-2.0\n#![allow(clippy::all)]\n#![allow(unused_parens)]\n#![cfg_attr(rustfmt, rustfmt_skip)]\n'
}

# Writes a generated mod.rs for a module directory: a `pub mod` declaration for
# every generated `.rs` file in the directory (the generated files reference
# each other as `super::`, so they must be sibling modules), followed by the
# given convenience re-export lines.
write_mod_rs() {
    dir="$1"
    doc="$2"
    shift 2
    {
        printf '// SPDX-License-Identifier: Apache-2.0\n'
        printf '// Generated by generate_antlr.sh. Do not edit.\n\n'
        printf '//! %s\n\n' "$doc"
        for rs in "$dir"/*.rs; do
            name=$(basename "$rs" .rs)
            [ "$name" = "mod" ] && continue
            printf 'pub mod %s;\n' "$name"
        done
        printf '\n'
        for use_line in "$@"; do
            printf '%s\n' "$use_line"
        done
    } > "$dir/mod.rs"
}

# Distribute the generated files into per-grammar module directories, mirroring
# the Python package's Substrait*/FuncTestCase* split.
rm -f "$TYPE_TARGET"/*.rs "$FTEST_TARGET"/*.rs
for f in tmp/substrait*.rs; do
    { header; cat "$f"; } > "$TYPE_TARGET/$(basename "$f")"
done
for f in tmp/functestcase*.rs; do
    { header; cat "$f"; } > "$FTEST_TARGET/$(basename "$f")"
done

# Generate the module wiring (mod.rs) for each directory.
write_mod_rs "$TYPE_TARGET" \
    "Generated ANTLR lexer, parser and listeners for the Substrait type grammar (\`SubstraitType.g4\`)." \
    "pub use substraittypelexer::SubstraitTypeLexer;" \
    "pub use substraittypeparser::SubstraitTypeParser;"
write_mod_rs "$FTEST_TARGET" \
    "Generated ANTLR lexer, parser and listeners for the Substrait function test case grammar (\`FuncTestCaseParser.g4\`)." \
    "pub use functestcaselexer::FuncTestCaseLexer;" \
    "pub use functestcaseparser::FuncTestCaseParser;"

# Cleanup.
rm -rf tmp
