# generated by datamodel-codegen:
#   filename:  dialect_schema.yaml

from __future__ import annotations
from enum import Enum
from dataclasses import dataclass
from typing import Any, Literal, TypeAlias


class SupportedTypes(Enum):
    BOOL = "BOOL"
    I8 = "I8"
    I16 = "I16"
    I32 = "I32"
    I64 = "I64"
    FP32 = "FP32"
    FP64 = "FP64"
    BINARY = "BINARY"
    FIXED_BINARY = "FIXED_BINARY"
    STRING = "STRING"
    VARCHAR = "VARCHAR"
    FIXED_CHAR = "FIXED_CHAR"
    PRECISION_TIME = "PRECISION_TIME"
    PRECISION_TIMESTAMP = "PRECISION_TIMESTAMP"
    PRECISION_TIMESTAMP_TZ = "PRECISION_TIMESTAMP_TZ"
    DATE = "DATE"
    TIME = "TIME"
    INTERVAL_COMPOUND = "INTERVAL_COMPOUND"
    INTERVAL_DAY = "INTERVAL_DAY"
    INTERVAL_YEAR = "INTERVAL_YEAR"
    UUID = "UUID"
    DECIMAL = "DECIMAL"
    STRUCT = "STRUCT"
    LIST = "LIST"
    MAP = "MAP"


class SupportedRelations(Enum):
    READ = "READ"
    FILTER = "FILTER"
    FETCH = "FETCH"
    AGGREGATE = "AGGREGATE"
    SORT = "SORT"
    JOIN = "JOIN"
    PROJECT = "PROJECT"
    SET = "SET"
    CROSS = "CROSS"
    REFERENCE = "REFERENCE"
    WRITE = "WRITE"
    DDL = "DDL"
    UPDATE = "UPDATE"
    HASH_JOIN = "HASH_JOIN"
    MERGE_JOIN = "MERGE_JOIN"
    NESTED_LOOP_JOIN = "NESTED_LOOP_JOIN"
    CONSISTENT_PARTITION_WINDOW = "CONSISTENT_PARTITION_WINDOW"
    EXCHANGE = "EXCHANGE"
    EXPAND = "EXPAND"


class SupportedExpressions(Enum):
    LITERAL = "LITERAL"
    SELECTION = "SELECTION"
    SCALAR_FUNCTION = "SCALAR_FUNCTION"
    WINDOW_FUNCTION = "WINDOW_FUNCTION"
    IF_THEN = "IF_THEN"
    SWITCH = "SWITCH"
    SINGULAR_OR_LIST = "SINGULAR_OR_LIST"
    MULTI_OR_LIST = "MULTI_OR_LIST"
    CAST = "CAST"
    SUBQUERY = "SUBQUERY"
    NESTED = "NESTED"
    DYNAMIC_PARAMETER = "DYNAMIC_PARAMETER"


class Notation(Enum):
    INFIX = "INFIX"
    POSTFIX = "POSTFIX"
    PREFIX = "PREFIX"
    FUNCTION = "FUNCTION"


@dataclass
class SystemMetadata:
    name: str | None = None
    notation: Notation | None = Notation.FUNCTION


@dataclass
class Variadic:
    min: int | None = None
    max: int | None = None


@dataclass
class DialectFunction:
    source: str
    name: str
    supported_impls: list[str]
    system_metadata: SystemMetadata | None = None
    required_options: dict[str, Any] | None = None
    variadic: Variadic | None = None


@dataclass
class SystemFunctionMetadata:
    name: str | None = None
    notation: Notation | None = Notation.FUNCTION


@dataclass
class SystemMetadata1:
    name: str | None = None
    supported_as_column: bool | None = None


@dataclass
class TypeBase:
    system_metadata: SystemMetadata1 | None = None


@dataclass
class SystemTypeMetadata:
    name: str | None = None
    supported_as_column: bool | None = None


@dataclass
class TypeBool:
    type: Literal["BOOL"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeI8:
    type: Literal["I8"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeI16:
    type: Literal["I16"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeI32:
    type: Literal["I32"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeI64:
    type: Literal["I64"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeFp32:
    type: Literal["FP32"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeFp64:
    type: Literal["FP64"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeBinary:
    type: Literal["BINARY"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeFixedBinary:
    type: Literal["FIXED_BINARY"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeString:
    type: Literal["STRING"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeVarchar:
    type: Literal["VARCHAR"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeFixedChar:
    type: Literal["FIXED_CHAR"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypePrecisionTime:
    type: Literal["PRECISION_TIME"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypePrecisionTimestamp:
    type: Literal["PRECISION_TIMESTAMP"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypePrecisionTimestampTz:
    type: Literal["PRECISION_TIMESTAMP_TZ"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeDate:
    type: Literal["DATE"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeTime:
    type: Literal["TIME"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeIntervalCompound:
    type: Literal["INTERVAL_COMPOUND"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeIntervalDay:
    type: Literal["INTERVAL_DAY"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeIntervalYear:
    type: Literal["INTERVAL_YEAR"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeUuid:
    type: Literal["UUID"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeDecimal:
    type: Literal["DECIMAL"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeStruct:
    type: Literal["STRUCT"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeList:
    type: Literal["LIST"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeMap:
    type: Literal["MAP"]
    system_metadata: SystemTypeMetadata | None = None


@dataclass
class TypeUserDefined:
    type: Literal["USER_DEFINED"]
    source: str
    name: str
    system_metadata: SystemTypeMetadata | None = None


class JoinType(Enum):
    INNER = "INNER"
    OUTER = "OUTER"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    LEFT_SEMI = "LEFT_SEMI"
    RIGHT_SEMI = "RIGHT_SEMI"
    LEFT_ANTI = "LEFT_ANTI"
    RIGHT_ANTI = "RIGHT_ANTI"
    LEFT_SINGLE = "LEFT_SINGLE"
    RIGHT_SINGLE = "RIGHT_SINGLE"
    LEFT_MARK = "LEFT_MARK"
    RIGHT_MARK = "RIGHT_MARK"


JoinTypes: TypeAlias = list[JoinType]


class ReadType(Enum):
    VIRTUAL_TABLE = "VIRTUAL_TABLE"
    LOCAL_FILES = "LOCAL_FILES"
    NAMED_TABLE = "NAMED_TABLE"
    EXTENSION_TABLE = "EXTENSION_TABLE"
    ICEBERG_TABLE = "ICEBERG_TABLE"


@dataclass
class ReadRelation:
    relation: Literal["READ"]
    read_types: list[ReadType] | None = None


@dataclass
class FilterRelation:
    relation: Literal["FILTER"]


@dataclass
class FetchRelation:
    relation: Literal["FETCH"]


@dataclass
class AggregateRelation:
    relation: Literal["AGGREGATE"]


@dataclass
class SortRelation:
    relation: Literal["SORT"]


@dataclass
class JoinRelation:
    relation: Literal["JOIN"]
    join_types: JoinTypes | None = None


@dataclass
class ProjectRelation:
    relation: Literal["PROJECT"]


class Operation(Enum):
    MINUS_PRIMARY = "MINUS_PRIMARY"
    MINUS_PRIMARY_ALL = "MINUS_PRIMARY_ALL"
    MINUS_MULTISET = "MINUS_MULTISET"
    INTERSECTION_PRIMARY = "INTERSECTION_PRIMARY"
    INTERSECTION_MULTISET = "INTERSECTION_MULTISET"
    INTERSECTION_MULTISET_ALL = "INTERSECTION_MULTISET_ALL"
    UNION_DISTINCT = "UNION_DISTINCT"
    UNION_ALL = "UNION_ALL"


@dataclass
class SetRelation:
    relation: Literal["SET"]
    operations: list[Operation] | None = None


@dataclass
class ExtensionSingleRelation:
    relation: Literal["EXTENSION_SINGLE"]
    message_types: list[str] | None = None


@dataclass
class ExtensionMultiRelation:
    relation: Literal["EXTENSION_MULTI"]
    message_types: list[str] | None = None


@dataclass
class ExtensionLeafRelation:
    relation: Literal["EXTENSION_LEAF"]
    message_types: list[str] | None = None


@dataclass
class CrossRelation:
    relation: Literal["CROSS"]


@dataclass
class ReferenceRelation:
    relation: Literal["REFERENCE"]


class WriteType(Enum):
    NAMED_TABLE = "NAMED_TABLE"
    EXTENSION_TABLE = "EXTENSION_TABLE"


@dataclass
class WriteRelation:
    relation: Literal["WRITE"]
    write_types: list[WriteType] | None = None


class WriteType1(Enum):
    NAMED_OBJECT = "NAMED_OBJECT"
    EXTENSION_OBJECT = "EXTENSION_OBJECT"


@dataclass
class DdlRelation:
    relation: Literal["DDL"]
    write_types: list[WriteType1] | None = None


@dataclass
class UpdateRelation:
    relation: Literal["UPDATE"]


@dataclass
class HashJoinRelation:
    relation: Literal["HASH_JOIN"]
    join_types: JoinTypes | None = None


@dataclass
class MergeJoinRelation:
    relation: Literal["MERGE_JOIN"]
    join_types: JoinTypes | None = None


@dataclass
class NestedLoopJoinRelation:
    relation: Literal["NESTED_LOOP_JOIN"]
    join_types: JoinTypes | None = None


@dataclass
class ConsistentPartitionWindowRelation:
    relation: Literal["CONSISTENT_PARTITION_WINDOW"]


class Kind(Enum):
    SCATTER_BY_FIELDS = "SCATTER_BY_FIELDS"
    SINGLE_TARGET = "SINGLE_TARGET"
    MULTI_TARGET = "MULTI_TARGET"
    ROUND_ROBIN = "ROUND_ROBIN"
    BROADCAST = "BROADCAST"


@dataclass
class ExchangeRelation:
    relation: Literal["EXCHANGE"]
    kinds: list[Kind] | None = None


class FieldType(Enum):
    SWITCHING_FIELD = "SWITCHING_FIELD"
    CONSTANT_FIELD = "CONSTANT_FIELD"


@dataclass
class ExpandRelation:
    relation: Literal["EXPAND"]
    field_types: list[FieldType] | None = None


@dataclass
class LiteralExpression:
    expression: Literal["LITERAL"]


@dataclass
class SelectionExpression:
    expression: Literal["SELECTION"]


@dataclass
class ScalarFunctionExpression:
    expression: Literal["SCALAR_FUNCTION"]


@dataclass
class WindowFunctionExpression:
    expression: Literal["WINDOW_FUNCTION"]


@dataclass
class IfThenExpression:
    expression: Literal["IF_THEN"]


@dataclass
class SwitchExpression:
    expression: Literal["SWITCH"]


@dataclass
class SingularOrListExpression:
    expression: Literal["SINGULAR_OR_LIST"]


@dataclass
class MultiOrListExpression:
    expression: Literal["MULTI_OR_LIST"]


class FailureOption(Enum):
    RETURN_NULL = "RETURN_NULL"
    THROW_EXCEPTION = "THROW_EXCEPTION"


@dataclass
class CastExpression:
    expression: Literal["CAST"]
    failure_options: list[FailureOption] | None = None


class SubqueryType(Enum):
    SCALAR = "SCALAR"
    IN_PREDICATE = "IN_PREDICATE"
    SET_PREDICATE = "SET_PREDICATE"
    SET_COMPARISON = "SET_COMPARISON"


@dataclass
class SubqueryExpression:
    expression: Literal["SUBQUERY"]
    subquery_types: list[SubqueryType] | None = None


class NestedType(Enum):
    STRUCT = "STRUCT"
    LIST = "LIST"
    MAP = "MAP"


@dataclass
class NestedExpression:
    expression: Literal["NESTED"]
    nested_types: list[NestedType] | None = None


@dataclass
class DynamicParameterExpression:
    expression: Literal["DYNAMIC_PARAMETER"]


@dataclass
class Dialect:
    name: str | None = None
    dependencies: dict[str, str] | None = None
    supported_types: (
        list[
            SupportedTypes
            | TypeBool
            | TypeI8
            | TypeI16
            | TypeI32
            | TypeI64
            | TypeFp32
            | TypeFp64
            | TypeBinary
            | TypeFixedBinary
            | TypeString
            | TypeVarchar
            | TypeFixedChar
            | TypePrecisionTime
            | TypePrecisionTimestamp
            | TypePrecisionTimestampTz
            | TypeDate
            | TypeTime
            | TypeIntervalCompound
            | TypeIntervalDay
            | TypeIntervalYear
            | TypeUuid
            | TypeDecimal
            | TypeStruct
            | TypeList
            | TypeMap
            | TypeUserDefined
        ]
        | None
    ) = None
    supported_relations: (
        list[
            SupportedRelations
            | ReadRelation
            | FilterRelation
            | FetchRelation
            | AggregateRelation
            | SortRelation
            | JoinRelation
            | ProjectRelation
            | SetRelation
            | ExtensionSingleRelation
            | ExtensionMultiRelation
            | ExtensionLeafRelation
            | CrossRelation
            | ReferenceRelation
            | WriteRelation
            | DdlRelation
            | UpdateRelation
            | HashJoinRelation
            | MergeJoinRelation
            | NestedLoopJoinRelation
            | ConsistentPartitionWindowRelation
            | ExchangeRelation
            | ExpandRelation
        ]
        | None
    ) = None
    supported_expressions: (
        list[
            SupportedExpressions
            | LiteralExpression
            | SelectionExpression
            | ScalarFunctionExpression
            | WindowFunctionExpression
            | IfThenExpression
            | SwitchExpression
            | SingularOrListExpression
            | MultiOrListExpression
            | CastExpression
            | SubqueryExpression
            | NestedExpression
            | DynamicParameterExpression
        ]
        | None
    ) = None
    supported_scalar_functions: list[DialectFunction] | None = None
    supported_aggregate_functions: list[DialectFunction] | None = None
    supported_window_functions: list[DialectFunction] | None = None
