// SPDX-License-Identifier: Apache-2.0

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SubstraitType.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Substrait.Antlr.SubstraitType {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SubstraitTypeParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISubstraitTypeListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SubstraitTypeParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartRule([NotNull] SubstraitTypeParser.StartRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SubstraitTypeParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartRule([NotNull] SubstraitTypeParser.StartRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SubstraitTypeParser.typeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStatement([NotNull] SubstraitTypeParser.TypeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SubstraitTypeParser.typeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStatement([NotNull] SubstraitTypeParser.TypeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boolean</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] SubstraitTypeParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolean</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] SubstraitTypeParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>i8</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI8([NotNull] SubstraitTypeParser.I8Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>i8</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI8([NotNull] SubstraitTypeParser.I8Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>i16</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI16([NotNull] SubstraitTypeParser.I16Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>i16</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI16([NotNull] SubstraitTypeParser.I16Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>i32</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI32([NotNull] SubstraitTypeParser.I32Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>i32</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI32([NotNull] SubstraitTypeParser.I32Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>i64</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI64([NotNull] SubstraitTypeParser.I64Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>i64</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI64([NotNull] SubstraitTypeParser.I64Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fp32</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFp32([NotNull] SubstraitTypeParser.Fp32Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fp32</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFp32([NotNull] SubstraitTypeParser.Fp32Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fp64</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFp64([NotNull] SubstraitTypeParser.Fp64Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fp64</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFp64([NotNull] SubstraitTypeParser.Fp64Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] SubstraitTypeParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] SubstraitTypeParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>binary</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary([NotNull] SubstraitTypeParser.BinaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>binary</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary([NotNull] SubstraitTypeParser.BinaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>date</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDate([NotNull] SubstraitTypeParser.DateContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>date</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDate([NotNull] SubstraitTypeParser.DateContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>intervalYear</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntervalYear([NotNull] SubstraitTypeParser.IntervalYearContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>intervalYear</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntervalYear([NotNull] SubstraitTypeParser.IntervalYearContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>uuid</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUuid([NotNull] SubstraitTypeParser.UuidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>uuid</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUuid([NotNull] SubstraitTypeParser.UuidContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fixedChar</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedChar([NotNull] SubstraitTypeParser.FixedCharContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fixedChar</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedChar([NotNull] SubstraitTypeParser.FixedCharContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>varChar</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarChar([NotNull] SubstraitTypeParser.VarCharContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>varChar</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarChar([NotNull] SubstraitTypeParser.VarCharContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fixedBinary</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedBinary([NotNull] SubstraitTypeParser.FixedBinaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fixedBinary</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedBinary([NotNull] SubstraitTypeParser.FixedBinaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>decimal</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] SubstraitTypeParser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>decimal</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] SubstraitTypeParser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>precisionIntervalDay</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecisionIntervalDay([NotNull] SubstraitTypeParser.PrecisionIntervalDayContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>precisionIntervalDay</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecisionIntervalDay([NotNull] SubstraitTypeParser.PrecisionIntervalDayContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>precisionIntervalCompound</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecisionIntervalCompound([NotNull] SubstraitTypeParser.PrecisionIntervalCompoundContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>precisionIntervalCompound</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecisionIntervalCompound([NotNull] SubstraitTypeParser.PrecisionIntervalCompoundContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>precisionTime</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecisionTime([NotNull] SubstraitTypeParser.PrecisionTimeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>precisionTime</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecisionTime([NotNull] SubstraitTypeParser.PrecisionTimeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>precisionTimestamp</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecisionTimestamp([NotNull] SubstraitTypeParser.PrecisionTimestampContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>precisionTimestamp</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecisionTimestamp([NotNull] SubstraitTypeParser.PrecisionTimestampContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>precisionTimestampTZ</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecisionTimestampTZ([NotNull] SubstraitTypeParser.PrecisionTimestampTZContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>precisionTimestampTZ</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecisionTimestampTZ([NotNull] SubstraitTypeParser.PrecisionTimestampTZContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>struct</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct([NotNull] SubstraitTypeParser.StructContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>struct</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct([NotNull] SubstraitTypeParser.StructContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>nStruct</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNStruct([NotNull] SubstraitTypeParser.NStructContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nStruct</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNStruct([NotNull] SubstraitTypeParser.NStructContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>list</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] SubstraitTypeParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>list</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] SubstraitTypeParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>map</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMap([NotNull] SubstraitTypeParser.MapContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>map</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMap([NotNull] SubstraitTypeParser.MapContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>func</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] SubstraitTypeParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>func</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] SubstraitTypeParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>userDefined</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUserDefined([NotNull] SubstraitTypeParser.UserDefinedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>userDefined</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUserDefined([NotNull] SubstraitTypeParser.UserDefinedContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>singleFuncParam</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.funcParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleFuncParam([NotNull] SubstraitTypeParser.SingleFuncParamContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>singleFuncParam</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.funcParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleFuncParam([NotNull] SubstraitTypeParser.SingleFuncParamContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcParamsWithParens</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.funcParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncParamsWithParens([NotNull] SubstraitTypeParser.FuncParamsWithParensContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcParamsWithParens</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.funcParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncParamsWithParens([NotNull] SubstraitTypeParser.FuncParamsWithParensContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numericLiteral</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.numericParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteral([NotNull] SubstraitTypeParser.NumericLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numericLiteral</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.numericParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteral([NotNull] SubstraitTypeParser.NumericLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numericParameterName</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.numericParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericParameterName([NotNull] SubstraitTypeParser.NumericParameterNameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numericParameterName</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.numericParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericParameterName([NotNull] SubstraitTypeParser.NumericParameterNameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numericExpression</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.numericParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericExpression([NotNull] SubstraitTypeParser.NumericExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numericExpression</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.numericParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericExpression([NotNull] SubstraitTypeParser.NumericExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SubstraitTypeParser.anyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnyType([NotNull] SubstraitTypeParser.AnyTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SubstraitTypeParser.anyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnyType([NotNull] SubstraitTypeParser.AnyTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SubstraitTypeParser.typeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDef([NotNull] SubstraitTypeParser.TypeDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SubstraitTypeParser.typeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDef([NotNull] SubstraitTypeParser.TypeDefContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfExpr</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfExpr([NotNull] SubstraitTypeParser.IfExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfExpr</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfExpr([NotNull] SubstraitTypeParser.IfExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Or</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr([NotNull] SubstraitTypeParser.OrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Or</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr([NotNull] SubstraitTypeParser.OrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultilineDefinition</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultilineDefinition([NotNull] SubstraitTypeParser.MultilineDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultilineDefinition</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultilineDefinition([NotNull] SubstraitTypeParser.MultilineDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDiv([NotNull] SubstraitTypeParser.MulDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDiv([NotNull] SubstraitTypeParser.MulDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSub([NotNull] SubstraitTypeParser.AddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSub([NotNull] SubstraitTypeParser.AddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Ternary</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTernary([NotNull] SubstraitTypeParser.TernaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Ternary</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTernary([NotNull] SubstraitTypeParser.TernaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParameterName</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterName([NotNull] SubstraitTypeParser.ParameterNameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParameterName</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterName([NotNull] SubstraitTypeParser.ParameterNameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeLiteral</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeLiteral([NotNull] SubstraitTypeParser.TypeLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeLiteral</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeLiteral([NotNull] SubstraitTypeParser.TypeLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Comparison</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] SubstraitTypeParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Comparison</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] SubstraitTypeParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>And</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd([NotNull] SubstraitTypeParser.AndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>And</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd([NotNull] SubstraitTypeParser.AndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpression</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpression([NotNull] SubstraitTypeParser.ParenExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpression</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpression([NotNull] SubstraitTypeParser.ParenExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionCall</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] SubstraitTypeParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionCall</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] SubstraitTypeParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] SubstraitTypeParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] SubstraitTypeParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality([NotNull] SubstraitTypeParser.EqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality([NotNull] SubstraitTypeParser.EqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralNumber</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralNumber([NotNull] SubstraitTypeParser.LiteralNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralNumber</c>
	/// labeled alternative in <see cref="SubstraitTypeParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralNumber([NotNull] SubstraitTypeParser.LiteralNumberContext context);
}
} // namespace Substrait.Antlr.SubstraitType
