// SPDX-License-Identifier: Apache-2.0

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FuncTestCaseParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Substrait.Antlr.FuncTestCase {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FuncTestCaseParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IFuncTestCaseParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.doc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoc([NotNull] FuncTestCaseParser.DocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeader([NotNull] FuncTestCaseParser.HeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersion([NotNull] FuncTestCaseParser.VersionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclude([NotNull] FuncTestCaseParser.IncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependency([NotNull] FuncTestCaseParser.DependencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.testGroupDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTestGroupDescription([NotNull] FuncTestCaseParser.TestGroupDescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.testCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTestCase([NotNull] FuncTestCaseParser.TestCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>scalarFuncTestGroup</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.testGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarFuncTestGroup([NotNull] FuncTestCaseParser.ScalarFuncTestGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aggregateFuncTestGroup</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.testGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateFuncTestGroup([NotNull] FuncTestCaseParser.AggregateFuncTestGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>windowFuncTestGroup</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.testGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowFuncTestGroup([NotNull] FuncTestCaseParser.WindowFuncTestGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] FuncTestCaseParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult([NotNull] FuncTestCaseParser.ResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] FuncTestCaseParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.aggFuncTestCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggFuncTestCase([NotNull] FuncTestCaseParser.AggFuncTestCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiArgAggregateFuncCall</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.aggFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiArgAggregateFuncCall([NotNull] FuncTestCaseParser.MultiArgAggregateFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compactAggregateFuncCall</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.aggFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompactAggregateFuncCall([NotNull] FuncTestCaseParser.CompactAggregateFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>singleArgAggregateFuncCall</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.aggFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleArgAggregateFuncCall([NotNull] FuncTestCaseParser.SingleArgAggregateFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.windowFuncTestCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowFuncTestCase([NotNull] FuncTestCaseParser.WindowFuncTestCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.windowFuncCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowFuncCall([NotNull] FuncTestCaseParser.WindowFuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.windowResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowResult([NotNull] FuncTestCaseParser.WindowResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.tableData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableData([NotNull] FuncTestCaseParser.TableDataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.tableRows"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableRows([NotNull] FuncTestCaseParser.TableRowsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.dataColumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataColumn([NotNull] FuncTestCaseParser.DataColumnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.columnValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnValues([NotNull] FuncTestCaseParser.ColumnValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] FuncTestCaseParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.qualifiedAggregateFuncArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedAggregateFuncArgs([NotNull] FuncTestCaseParser.QualifiedAggregateFuncArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.aggregateFuncArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateFuncArgs([NotNull] FuncTestCaseParser.AggregateFuncArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.qualifiedAggregateFuncArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedAggregateFuncArg([NotNull] FuncTestCaseParser.QualifiedAggregateFuncArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.aggregateFuncArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateFuncArg([NotNull] FuncTestCaseParser.AggregateFuncArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.windowFuncArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowFuncArgs([NotNull] FuncTestCaseParser.WindowFuncArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.windowFuncArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowFuncArg([NotNull] FuncTestCaseParser.WindowFuncArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericLiteral([NotNull] FuncTestCaseParser.NumericLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] FuncTestCaseParser.FloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.nullArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullArg([NotNull] FuncTestCaseParser.NullArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntArg([NotNull] FuncTestCaseParser.IntArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.floatArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatArg([NotNull] FuncTestCaseParser.FloatArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.decimalArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalArg([NotNull] FuncTestCaseParser.DecimalArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.booleanArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanArg([NotNull] FuncTestCaseParser.BooleanArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.stringArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringArg([NotNull] FuncTestCaseParser.StringArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.dateArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateArg([NotNull] FuncTestCaseParser.DateArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intervalYearArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntervalYearArg([NotNull] FuncTestCaseParser.IntervalYearArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intervalDayArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntervalDayArg([NotNull] FuncTestCaseParser.IntervalDayArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intervalCompoundArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntervalCompoundArg([NotNull] FuncTestCaseParser.IntervalCompoundArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.fixedCharArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixedCharArg([NotNull] FuncTestCaseParser.FixedCharArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.varCharArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarCharArg([NotNull] FuncTestCaseParser.VarCharArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.fixedBinaryArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixedBinaryArg([NotNull] FuncTestCaseParser.FixedBinaryArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.precisionTimeArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecisionTimeArg([NotNull] FuncTestCaseParser.PrecisionTimeArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.precisionTimestampArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecisionTimestampArg([NotNull] FuncTestCaseParser.PrecisionTimestampArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.precisionTimestampTZArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecisionTimestampTZArg([NotNull] FuncTestCaseParser.PrecisionTimestampTZArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.listArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListArg([NotNull] FuncTestCaseParser.ListArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.structArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructArg([NotNull] FuncTestCaseParser.StructArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.mapArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapArg([NotNull] FuncTestCaseParser.MapArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.userDefinedArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUserDefinedArg([NotNull] FuncTestCaseParser.UserDefinedArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.lambdaArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaArg([NotNull] FuncTestCaseParser.LambdaArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.funcCallArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallArg([NotNull] FuncTestCaseParser.FuncCallArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.enumArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumArg([NotNull] FuncTestCaseParser.EnumArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.literalList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralList([NotNull] FuncTestCaseParser.LiteralListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.literalStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralStruct([NotNull] FuncTestCaseParser.LiteralStructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.literalMap"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralMap([NotNull] FuncTestCaseParser.LiteralMapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.mapEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapEntry([NotNull] FuncTestCaseParser.MapEntryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.compoundLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundLiteral([NotNull] FuncTestCaseParser.CompoundLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.literalLambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralLambda([NotNull] FuncTestCaseParser.LiteralLambdaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>singleParam</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleParam([NotNull] FuncTestCaseParser.SingleParamContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tupleParams</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleParams([NotNull] FuncTestCaseParser.TupleParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaBody([NotNull] FuncTestCaseParser.LambdaBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataType([NotNull] FuncTestCaseParser.DataTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolean</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] FuncTestCaseParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] FuncTestCaseParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>float</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat([NotNull] FuncTestCaseParser.FloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] FuncTestCaseParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binary</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary([NotNull] FuncTestCaseParser.BinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>date</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] FuncTestCaseParser.DateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intervalYear</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntervalYear([NotNull] FuncTestCaseParser.IntervalYearContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>uuid</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUuid([NotNull] FuncTestCaseParser.UuidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>userDefined</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUserDefined([NotNull] FuncTestCaseParser.UserDefinedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.userDefinedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUserDefinedType([NotNull] FuncTestCaseParser.UserDefinedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.booleanType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanType([NotNull] FuncTestCaseParser.BooleanTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.stringType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringType([NotNull] FuncTestCaseParser.StringTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.binaryType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryType([NotNull] FuncTestCaseParser.BinaryTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntType([NotNull] FuncTestCaseParser.IntTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.floatType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatType([NotNull] FuncTestCaseParser.FloatTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.dateType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateType([NotNull] FuncTestCaseParser.DateTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intervalYearType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntervalYearType([NotNull] FuncTestCaseParser.IntervalYearTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intervalDayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntervalDayType([NotNull] FuncTestCaseParser.IntervalDayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.intervalCompoundType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntervalCompoundType([NotNull] FuncTestCaseParser.IntervalCompoundTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.fixedCharType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixedCharType([NotNull] FuncTestCaseParser.FixedCharTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.varCharType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarCharType([NotNull] FuncTestCaseParser.VarCharTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.fixedBinaryType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixedBinaryType([NotNull] FuncTestCaseParser.FixedBinaryTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.decimalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalType([NotNull] FuncTestCaseParser.DecimalTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.precisionTimeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecisionTimeType([NotNull] FuncTestCaseParser.PrecisionTimeTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.precisionTimestampType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecisionTimestampType([NotNull] FuncTestCaseParser.PrecisionTimestampTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.precisionTimestampTZType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecisionTimestampTZType([NotNull] FuncTestCaseParser.PrecisionTimestampTZTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>list</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.listType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] FuncTestCaseParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.structType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructType([NotNull] FuncTestCaseParser.StructTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.mapType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapType([NotNull] FuncTestCaseParser.MapTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.funcType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncType([NotNull] FuncTestCaseParser.FuncTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>singleFuncParam</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.funcParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleFuncParam([NotNull] FuncTestCaseParser.SingleFuncParamContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcParamsWithParens</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.funcParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncParamsWithParens([NotNull] FuncTestCaseParser.FuncParamsWithParensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.parameterizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterizedType([NotNull] FuncTestCaseParser.ParameterizedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>integerLiteral</c>
	/// labeled alternative in <see cref="FuncTestCaseParser.numericParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] FuncTestCaseParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.substraitError"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubstraitError([NotNull] FuncTestCaseParser.SubstraitErrorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.funcOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncOption([NotNull] FuncTestCaseParser.FuncOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.optionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionName([NotNull] FuncTestCaseParser.OptionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionValue([NotNull] FuncTestCaseParser.OptionValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.funcOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncOptions([NotNull] FuncTestCaseParser.FuncOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.nonReserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonReserved([NotNull] FuncTestCaseParser.NonReservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FuncTestCaseParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] FuncTestCaseParser.IdentifierContext context);
}
} // namespace Substrait.Antlr.FuncTestCase
